### ISSUE TITLE
Error in setwd(x) : cannot change working directory

### ISSUE THREAD

**Issue by bateyt** [trinker/reports#51]
Software:
Windows 7 (32-bit)
R-3.0.2
RStudio (Version 0.98.501)
reports 0.2.0

First time trying to use reports package on new machine with Windows 7.  Never run into this error (below) using Windows XP.  Thanks.

> library(reports)
> new_report("new")
> Error in setwd(x) : cannot change working directory

**Comment by SergeyBolotin** [comment]
i got the same problem when use "~" in the path. If i use full path "C:/User...." there is not problems.

**Comment by SindhuraElluri** [comment]
Hi, I ran into a similar problem. 
Below is my file structure-> C:/Users/esindhura25/Desktop/Research/Southwesterndata/Grade6/(S34,S35)
ecah of S34 or S35 contain a log file. Below is the code I am trying to execute

setwd('C:/Users/esindhura25/Desktop/Research/Southwesterndata/Grade6')
students <- list.files()
for(std in students)
{
  setwd(paste(std, '/log/', sep = ""))
  unlink('*.ng3', recursive = FALSE, force = FALSE)
  #setwd(paste('C:/Users/esindhura25/Desktop/Research/Southwesterndata/',fileDir, sep = ""))
}

But I am getting the below error . Please advise

Error in setwd(paste(std, "/log/", sep = "")) : 
  cannot change working directory

**Comment by heeby89** [comment]
@SindhuraElluri No one answered?

**Comment by trinker** [comment]
@heeby89 as far as I can tell that code has nothing to do with this package.  I'm guessing @SindhuraElluri got a similar error and a google search lead here.  That post probably belongs on stackoverflow not here if that is the case.

I agree that this behavior should be changed but don't forsee it until 2017.  Pull requests are welcome.  In the mean time it should work to explicitly change your working directory to the location you wish to add a project to (using `setwd`) before using `new_report`

**Comment by VytasHub** [comment]
getwd() didn't work for me too.

I was able to change my working directory throw settings.

Tool>Global Options...>General

**Comment by GabiUp2** [comment]
Have you tried opening your editor with administration priviliges? It worked for me.

**Comment by ghost** [comment]
I had the same problem with changing the working directory 

With the same getwd commend giving me the following error:
> setwd('F:/ContactFrom_v17/:')
Error in setwd("F:/ContactFrom_v17/:") : cannot change working directory

But @VytasHub @SindhuraElluri  with simple understanding and manual effort I was able to change the directory 
I am currently using RStusio 1.1.453 and it has a button on right of the window which is 'Go to directory'
Simply selecting that i was able to change the directory easily.

**Comment by ketra21** [comment]
RStusio in window 10.
@AshwInDu  maybe your setwd("...") is not right. you can drop the second ":",change it like this:
`setwd('F:/ContactFrom_v17')`
have a try!

**Comment by fereshtehizadi** [comment]
Yes I have already found the jar files but I don't know how to address them 

https://github.com/edroaldo/cellrouter/tree/master/CellRouter/dist/lib


https://github.com/edroaldo/cellrouter/tree/master/CellRouter/lib

**Comment by bzamanloo** [comment]
I had the same error in Rtusio on Ubuntu 16.04. I removed the "~" from my new path and the error was resolved.

**Comment by Kalondepatrick** [comment]
Am a beginner in R. I came across a slightly different error message. And i hereby share it here so that it can possibly help newbies in R.  My problem was that i was specifying the root directory as below

`setwd("Users/Patrick/Scripts")`

Then when i specified the root directory as the code below, it just worked pretty fine. 

`setwd("C:/Users/Patrick/Scripts")`

In this way, i realized that there is more flexibility that one can specify a USB drive to be a working directory. Pretty cool.

**Comment by Ahlam840** [comment]
1-getwe()
2-then go to the lower right window 
3- files tab and choose the folder that you want 
4- go to more tab and choose set as working directory the setwd() will show automatically in 
console window withe the new directory you choose 
5- and to see file in that directory  dir() 
it  It worked for me.
