### ISSUE TITLE
Several issues using reports

### ISSUE THREAD

**Issue by sapphire75710** [trinker/reports#57]
Hi there, 

I am using reports and run into some problems I cannot solve.

1. How to change the font in the title?

I use the following code in Rmd, but when the title is too long, I will end up with a whole page with 
Title.

%Title
% Name
% Date

2. How to not include the r code, I use the following code
```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(cache = TRUE)
```
The r code is not included in the rendered html, but still in the html after I use reveal.js()

3. How to NOT let the content showing one by one, I use the following code
# slide 1
* cotent 1
* content 2
* content 3

I also tried using - instead of *, but still not working.

4. The command reveal.js(), I cannot just use reveal.js(). But I need to speciefy the in.file name.

Thanks inadvance.

**Comment by trinker** [comment]
You are using the version from CRAN.  The development version no longer uses `reveal.js` but incorporates the functionality of the slidify package.  Install the dev version:

```r
library(devtools)
#Install the development versions of slidify and its libraries
install_github('slidify', 'ramnathv', ref = 'dev')
install_github('slidifyLibraries', 'ramnathv', ref = 'dev')
install_github("rstudio/rmarkdown")

install_github("trinker/reports")
```

This change font size on the title slides requires changing the css files.  Because the **reports** package now uses [slidify](https://github.com/ramnathv/slidify) for this task questions of this nature can be directed to the [**slidify** GitHub issues page](https://github.com/ramnathv/slidify/issues) after you've done a thorough search of the topic yourself.

**Comment by sapphire75710** [comment]
Hi

Thanks for the reply.

I turned to CRAN reports because of the failure to install reports from github. 

The installation of first 3 (slidify, slidyLibraries and rmarkdown ) are fine, but the installation of reports give the following error:

Downloading github repo trinker/reports@master
Installing reports
Skipping 1 packages not available: slidify
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/ry/4thd15j13qj029qgtkywfvbh0000gn/T/Rtmpf68wr7/devtools4d74e2d051d/trinker-reports-de8e33a'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

ERROR: failed to lock directory ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library’ for modifying
Try removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/00LOCK-trinker-reports-de8e33a’
Error: Command failed (3)

**Comment by trinker** [comment]
You have several issues.  First you have a 00LOCK you need to fix:

```r
Try removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/00LOCK-trinker-reports-de8e33a’
```

I discuss here how one removes this 00LOCK: http://stackoverflow.com/a/26573219/1000343

Secondly, you haven't installed slidify first, per my instructions above as this is a dependency that must be installed.  The message:

```r
Downloading github repo trinker/reports@master
Installing reports
Skipping 1 packages not available: slidify
```
 
tells us you have not installed slidify first.  You say 

> The installation of first 3 (slidify, slidyLibraries and rmarkdown ) are fine

but this can't be the case as slidify is unavailable unless maybe the 00LOCK.  One way to test is to use:

```r
packageVersion("slidify")
```

and report back the result.  You'll get either:

```r
[1] ‘0.3.52’

## or...

Error in packageVersion("slidifyk") : package ‘slidify’ not found
```

**Comment by trinker** [comment]
Also I think this script is more readable and easier to use to install the dependencies + **reports*** dev:

```r
if (!require("pacman")) install.packages("pacman")
pacman::p_load_gh(
    "ramnathv/slidify@dev",
    "ramnathv/slidifyLibraries@dev",
    "rstudio/rmarkdown",
    "trinker/reports"
)
```

I added this to the README.md

**Comment by sapphire75710** [comment]
Oh, Thanks again!

The last script works perfect!

**Comment by trinker** [comment]
Excellent and thanks on the **pacman** version script.  I think it makes life easier.  If you have questions about manipulating individual slides in slidify Ramnath is very responsive and quick to help.
