### ISSUE TITLE
"" does not exist in current working directory

### ISSUE THREAD

**Issue by hecabomb** [trinker/reports#58]
Hi guys I'm having difficulty loading .xlsx into RStudio - I'm not sure why RStudio can't see the file.
Am I specify the path for read_excel() wrong?
Any ideas? Pretty new at R.

Thanks!

Windows 10 (64-bit)
Version 0.99.491
read.xl 0.1.0

> getwd()
> [1] "C:/Users/user/Documents/Work"
> read_excel(system.file("C:/Users/user/Documents/Work/Data.xlsx"))
> Error: '' does not exist in current working directory ('C:/Users/user/Documents/Work').

**Comment by trinker** [comment]
This has nothing to do with the **reports** package and thus am closing.  If I've made an error please feel free to reopen.  The **readxl** package has it's own GtHub page.  I'd ask there or StackOverflow.
